const system = require("../../setting/system")
const dashboard = require("./dashboard")
const products = require("./products")
const category = require("./products-category")
const role = require("./role")
const premisson = require("./premisson")
const user = require("./user")
const myaccout = require("./myaccout")
const routerpravite = require("../../middlewares/auth/routerpravite")
const chat = require("./chat")
const accountreview = require("./accrv")
const checkedinvoice = require("./checkedinvoice")
const invoice = require("./invoice")
const voucher = require("./voucher")
const maintain = require("./maintain")
const chart = require("./chart")
const chartfloor = require("./chartfloor")
const checkproducts = require("./checkproducts")
const SEO = require("./SEO")
const dashboardadmin = require("./dashboardadmin")
const middlemaintain = require("../../middlewares/admin/routermaintain")
module.exports = (app) =>{
    const admin = system.prefixAdmin
    app.use(`/${admin}/dashboard`,routerpravite,dashboard)
    app.use(`/${admin}/dashboardadmin`,routerpravite,dashboardadmin)
    app.use(`/${admin}/products`,routerpravite,products)
    app.use(`/${admin}/category`,routerpravite,category)
    app.use(`/${admin}/role`,routerpravite,role)
    app.use(`/${admin}/premisson`,routerpravite,premisson)
    app.use(`/${admin}/user`,routerpravite,user)
    app.use(`/${admin}/myaccount`,middlemaintain,myaccout)
    app.use(`/${admin}/chat`,routerpravite,chat)
    app.use(`/${admin}/accountreview`,routerpravite,accountreview)
    app.use(`/${admin}/checkinvoice`,routerpravite,checkedinvoice)
    app.use(`/${admin}/invoice`,routerpravite,invoice)
    app.use(`/${admin}/voucher`,routerpravite,voucher)
    app.use(`/${admin}/maintain`,middlemaintain,maintain)
    app.use(`/${admin}/chart`,routerpravite,chart)
    app.use(`/${admin}/chartfloor`,routerpravite,chartfloor)
    app.use(`/${admin}/checkproducts`,routerpravite,checkproducts)
    app.use(`/${admin}/SEO`,routerpravite,SEO)
}